//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralDashboard.Models.Abastecimiento
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BD_ABASTECIMIENTOEntities1 : DbContext
    {
        public BD_ABASTECIMIENTOEntities1()
            : base("name=BD_ABASTECIMIENTOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<RPT_CEM_CENABAST_Result> RPT_CEM_CENABAST(Nullable<int> aA, Nullable<bool> esInsumo)
        {
            var aAParameter = aA.HasValue ?
                new ObjectParameter("AA", aA) :
                new ObjectParameter("AA", typeof(int));
    
            var esInsumoParameter = esInsumo.HasValue ?
                new ObjectParameter("esInsumo", esInsumo) :
                new ObjectParameter("esInsumo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_CEM_CENABAST_Result>("RPT_CEM_CENABAST", aAParameter, esInsumoParameter);
        }
    }
}
